load("@rules_python//python:defs.bzl", "py_library", "py_test")
load("@emz_deps//:requirements.bzl", "requirement")

py_library(
    name = "pointnet",
    srcs = ["pointnet.py"],
    visibility = ["//visibility:public"],
)
